name: Docs
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    container:
      image: crystallang/crystal
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
      - name: Install rsync 📚
        run: |
          apt-get update && apt-get install -y rsync
      - name: Build docs
        run: crystal docs --project-name Representer --project-version 1.2.0
      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@ec9c88baef04b842ca6f0a132fd61c762aa6c1b0
        with:
          branch: gh-pages
          folder: docs # The folder the action should deploy.
          clean: true
